package com.mgmemo.app.ui.theme

import androidx.compose.ui.graphics.Color

// ---------- 浅色（Light）----------
val GreenPrimary = Color(0xFF3B6939)
val OnGreenPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFFBCF2B0)
val OnGreenPrimaryContainer = Color(0xFF002201)
val GreenSecondary = Color(0xFF53634E)
val OnGreenSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFD6E8CD)
val OnGreenSecondaryContainer = Color(0xFF111F0F)
val GreenTertiary = Color(0xFF386568)
val OnGreenTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFBBEBEE)
val OnGreenTertiaryContainer = Color(0xFF002022)
val GreenError = Color(0xFFBA1A1A)
val OnGreenError = Color(0xFFFFFFFF)
val GreenErrorContainer = Color(0xFFFFDAD6)
val OnGreenErrorContainer = Color(0xFF410002)
val GreenBackground = Color(0xFFF9FAF2)
val OnGreenBackground = Color(0xFF1A1C19)
val GreenSurface = Color(0xFFF9FAF2)
val OnGreenSurface = Color(0xFF1A1C19)
val GreenSurfaceVariant = Color(0xFFDEE5D8)
val OnGreenSurfaceVariant = Color(0xFF424940)
val GreenOutline = Color(0xFF727970)
val GreenOutlineVariant = Color(0xFFC2C9BC)

// ---------- 深色（Dark）----------
val DarkPrimary = Color(0xFFA1D797)
val OnDarkPrimary = Color(0xFF0B3A0F)
val DarkPrimaryContainer = Color(0xFF245126)
val OnDarkPrimaryContainer = Color(0xFFBCF2B0)
val DarkSecondary = Color(0xFFBACCB2)
val OnDarkSecondary = Color(0xFF253422)
val DarkSecondaryContainer = Color(0xFF3B4B37)
val OnDarkSecondaryContainer = Color(0xFFD6E8CD)
val DarkTertiary = Color(0xFF9FCFD3)
val OnDarkTertiary = Color(0xFF00363A)
val DarkTertiaryContainer = Color(0xFF1E4D50)
val OnDarkTertiaryContainer = Color(0xFFBBEBEE)
val DarkError = Color(0xFFFFB4AB)
val OnDarkError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val OnDarkErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF12140F)
val OnDarkBackground = Color(0xFFE2E3DC)
val DarkSurface = Color(0xFF12140F)
val OnDarkSurface = Color(0xFFE2E3DC)
val DarkSurfaceVariant = Color(0xFF424940)
val OnDarkSurfaceVariant = Color(0xFFC2C9BC)
val DarkOutline = Color(0xFF8C9387)
val DarkOutlineVariant = Color(0xFF424940)

// ---------- 护眼绿（Eye Green）----------
val EyeBackground = Color(0xFFC7EDCC)
val OnEyeBackground = Color(0xFF17321D)
val EyeSurface = Color(0xFFC7EDCC)
val OnEyeSurface = Color(0xFF17321D)
val EyeSurfaceVariant = Color(0xFFB3D9B8)
val OnEyeSurfaceVariant = Color(0xFF2C4A33)
val EyePrimary = Color(0xFF2E6B3A)
val OnEyePrimary = Color(0xFFFFFFFF)
val EyePrimaryContainer = Color(0xFF9CD6A6)
val OnEyePrimaryContainer = Color(0xFF0A2E12)
val EyeOutline = Color(0xFF5E7A63)
val EyeOutlineVariant = Color(0xFF93AF98)